# Generated by Django 3.0.3 on 2020-03-01 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('requested_on', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('DISBURSED', 'DISBURSED')], max_length=255)),
                ('requester', models.CharField(max_length=255)),
            ],
        ),
    ]
