# Generated by Django 3.0.3 on 2020-03-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('DISBURSED', 'DISBURSED')], default='PENDING', max_length=255),
        ),
    ]
