# Generated by Django 3.0.7 on 2020-06-13 03:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='requested_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
