# Generated by Django 3.0.4 on 2020-03-17 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-updated_at']},
        ),
    ]
