# Generated by Django 3.0.7 on 2020-06-13 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_auto_20200613_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='approval_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='requested_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
