# Generated by Django 3.0.4 on 2020-03-21 05:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_auto_20200317_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='submitted_by_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
