# Generated by Django 3.0.4 on 2020-04-11 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_expense_submitted_by_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='approval_date',
            field=models.DateField(auto_now=True),
        ),
    ]
