# Generated by Django 3.0.4 on 2020-04-12 20:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_expense_approval_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='approved_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
