# Generated by Django 3.0.4 on 2020-04-12 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_expense_approved_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
