# Generated by Django 3.0.3 on 2020-03-01 08:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200301_0515'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tel_no',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=30, unique=True, verbose_name='user name'),
        ),
    ]
