# Generated by Django 3.0.3 on 2020-03-01 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('amount_charged', models.FloatField()),
                ('client', models.CharField(max_length=255)),
                ('purpose', models.CharField(choices=[('MORTGAGE', 'MORTGAGE'), ('EXPROPRIATION', 'EXPROPRIATION'), ('EVALUATION', 'EVALUATION')], max_length=100)),
                ('inspection_date', models.DateField()),
                ('report_payed_for', models.BooleanField(default=False)),
                ('reason_for_not_paying', models.TextField()),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('owner', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
