# Generated by Django 3.0.4 on 2020-06-01 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='plot_no',
            new_name='upi',
        ),
        migrations.AlterField(
            model_name='report',
            name='amount',
            field=models.FloatField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='report',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
