# Generated by Django 3.0.4 on 2020-04-05 13:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_file',
            field=models.FileField(default=datetime.datetime(2020, 4, 5, 13, 41, 17, 587484, tzinfo=utc), upload_to='documents'),
            preserve_default=False,
        ),
    ]
