# Generated by Django 3.0.7 on 2020-06-27 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20200601_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='approval_date',
            field=models.DateField(null=True),
        ),
    ]
