# Generated by Django 3.0.7 on 2020-06-27 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_report_approval_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='approved_at',
            field=models.DateTimeField(null=True),
        ),
    ]
