# Generated by Django 3.0.4 on 2020-04-11 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_report_report_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created_at']},
        ),
    ]
