# Generated by Django 3.0.7 on 2021-02-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_report_approved_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='purpose',
            field=models.CharField(choices=[('MORTGAGE', 'MORTGAGE'), ('EXPROPRIATION', 'EXPROPRIATION'), ('EVALUATION', 'EVALUATION'), ('LAND SUBDIVISION', 'LAND SUBDIVISION'), ('CONSTRUCTION STAKEOUTS', 'CONSTRUCTION STAKEOUTS'), ('ZONING PLATS', 'ZONING PLATS'), ('VOLUME ANALYSIS SURVEY', 'VOLUME ANALYSIS SURVEY'), ('TOPOGRAPHIC SURVEYS', 'TOPOGRAPHIC SURVEYS'), ('FLOODING ANALYSIS', 'FLOODING ANALYSIS'), ('LOT GRADING PLANS', 'LOT GRADING PLANS'), ('HYDRO GRAPHIC SURVEY', 'HYDRO GRAPHIC SURVEY')], max_length=100),
        ),
    ]
