# Generated by Django 3.0.4 on 2020-03-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20200311_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='purpose',
            field=models.CharField(choices=[('SELECT', 'SELECT'), ('MORTGAGE', 'MORTGAGE'), ('EXPROPRIATION', 'EXPROPRIATION'), ('EVALUATION', 'EVALUATION')], max_length=100),
        ),
    ]
