# Generated by Django 3.0.4 on 2020-03-11 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_auto_20200311_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='amount',
            field=models.FloatField(max_length=255),
        ),
        migrations.AlterField(
            model_name='report',
            name='purpose',
            field=models.CharField(choices=[('MORTGAGE', 'MORTGAGE'), ('EXPROPRIATION', 'EXPROPRIATION'), ('EVALUATION', 'EVALUATION')], max_length=100),
        ),
    ]
