# Generated by Django 3.0.4 on 2020-04-12 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_auto_20200412_0441'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reports.Report'),
        ),
    ]
