# Generated by Django 3.0.4 on 2020-03-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_auto_20200311_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='delivery_date',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='report',
            name='inspection_date',
            field=models.CharField(max_length=255),
        ),
    ]
