# Generated by Django 3.0.4 on 2020-04-12 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_auto_20200412_0709'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
