# Generated by Django 3.0.4 on 2020-04-12 22:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_report_verified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='verified_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
