# Generated by Django 3.0.4 on 2020-03-31 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(default='email@gmail.com', max_length=254, verbose_name='email'),
            preserve_default=False,
        ),
    ]
